name: goi
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.10.13
  - pip=22.3.1
  - pytorch==2.2.0
  - torchvision==0.17.0
  - torchaudio==2.2.0
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - tqdm
  - einops
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - trimesh
    - kiui
    - pymeshlab
    - rembg
    - open3d
    - scipy
    - dearpygui
    - omegaconf
    - open_clip_torch
    - transformations
    - transformers==4.38.1
    - yapf
    - pycocotools
    - clip@git+https://github.com/openai/CLIP.git