load: logs/room


source_path: data/mipnerf360/room
# source_path: data/mipnerf360_ov/room/bowl_on_the_table

images: images_8/

prompt: ""
negative_prompt: "ugly, bad anatomy, blurry, pixelated, obscure, unnatural colors, poor lighting, dull, unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions."
target_prompt: "sofachair"
target_res_prompt: "sofachair"


radius: 2

outdir: output/
save_path: edit_room
gui: True

H: 389 
W: 519 

fovy: 60
sh_degree: 3
input: null
preload: null

save_guidance: true
save_guidance_interval: 5
sd_guidance_scale: 100

# training option
lambda_sd: 10
max_epochs: 40
batch_size: 2

# original option in dreamgaussian
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 300
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.001 #0.005 
rotation_lr: 0.01 #0.005 
semantic_lr: 0.005

position_finetune: True
feature_finetune: True
opacity_finetune: True
scaling_finetune: True
rotation_finetune: True
semantic_finetune: True

percent_dense: 0.01
density_start_iter: 0
density_end_iter: 3400
densification_interval: 100
opacity_reset_interval: 700
densify_grad_threshold: 0.01