load: output/360_room/point_cloud/iteration_1500  # path to the model to load
source_path: datasets/360/room  # path to the dataset

images: images_8/  # change this to images_2/4/8 (if existing) for faster loading
target_prompt: "sofa in dark green"  # default text prompt for the segmentation
target_res_prompt: "sofa in dark green"  # prompt for res, same as target_prompt

vlm: ape  # [ape, clip]
radius: 2
outdir: output/exp
save_path: m360  # saving in <outdir>/<save_path>

### rendering options
gui: True
white_background: False
H: 520
W: 780
fovy: 60
sh_degree: 3

### inpainting options
prompt: ""
negative_prompt: "ugly, bad anatomy, blurry, pixelated, obscure, unnatural colors, poor lighting, dull, unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions."
save_guidance: true
save_guidance_interval: 5
sd_guidance_scale: 100

### training options
lambda_sd: 10
max_epochs: 40
batch_size: 2

### options for finetuning, not used
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 300
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.001 #0.005 
rotation_lr: 0.01 #0.005 
semantic_lr: 0.005

position_finetune: True
feature_finetune: True
opacity_finetune: True
scaling_finetune: True
rotation_finetune: True
semantic_finetune: True

percent_dense: 0.01
density_start_iter: 0
density_end_iter: 3400
densification_interval: 100
opacity_reset_interval: 700
densify_grad_threshold: 0.01